import { CtaButton } from "@/components/ui/button";
import { hero } from "@/content/copy";
import { LogoMarquee } from "@/components/ui/logo-marquee";

/**
 * Full-bleed background video behind the headline.
 *
 * Server component — no JS. The poster sits on the wrapper as a background
 * image and the video paints over it, so hiding the video under
 * `prefers-reduced-motion` (see globals.css) leaves the still frame in place
 * with no script and no flash.
 *
 * `muted` and `playsInline` are both load-bearing: iOS Safari refuses to
 * autoplay without them. `poster` also covers the gap before first frame.
 *
 * Height is an exact `h-dvh`, not a `min-h`. The composition depends on it:
 * the content container is `calc(100% - 100px)`, reserving the logo band, and
 * a min-height would let a long line push the band off the fold. `dvh` rather
 * than `vh` because on mobile the collapsing URL bar changes `vh` mid-scroll
 * and the hero would visibly resize under the reader.
 *
 * The negative margin cancels the padding `main` reserves for the chrome, so
 * the hero starts at y:0 with the bar and nav floating over it.
 */
export function Hero() {
  return (
    <section className="relative isolate -mt-[var(--header-h)] flex h-dvh flex-col items-center overflow-clip bg-ground">
      {/* Background stack: video (0), scrim (1), grain (2), content (10).
          POSITIVE z-indexes on purpose. These were -30/-20/-10 with the
          content at auto, which renders identically but buries the video
          three layers deep behind the section's own background — and Chrome
          then treats it as occluded and stops decoding, so the hero silently
          freezes on its poster while `currentTime` keeps advancing. Keep the
          video in normal stacking order. */}
      <div
        aria-hidden
        className="absolute inset-0 z-0 bg-ground bg-cover bg-center"
        style={{ backgroundImage: "url(/video/hero-poster.webp)" }}
      >
        <video
          className="hero-video h-full w-full object-cover"
          autoPlay
          muted
          loop
          playsInline
          preload="auto"
          poster="/video/hero-poster.webp"
          tabIndex={-1}
        >
          {/* `media` filters the source list before selection, so under
              reduced motion nothing is fetched at all — not fetched and then
              hidden. The poster behind is already doing the work. */}
          <source
            src="/video/hero.webm"
            type="video/webm"
            media="(prefers-reduced-motion: no-preference)"
          />
          <source
            src="/video/hero.mp4"
            type="video/mp4"
            media="(prefers-reduced-motion: no-preference)"
          />
        </video>
      </div>

      {/* Scrim — TWO stops, 0.44 to 0.60, in the ground colour rather than in
          black. This replaced a five-stop gradient that opened at 0.93 and was
          derived per-clip from measured band luma; it crushed the footage and
          the sky went with it.

          What makes two stops safe here is that nothing in the text block
          relies on the scrim any more: every run in the hero is pure white,
          the type is much larger than it was, and the reference sets it the
          same way. If a future clip has a blown highlight drifting under the
          text, re-derive rather than deepening this uniformly. */}
      <div
        aria-hidden
        className="absolute inset-0 z-[1]"
        style={{
          backgroundImage:
            "linear-gradient(rgba(21,21,21,0.44) 0%, rgba(21,21,21,0.60) 105%)",
        }}
      />

      {/* Grain. A 256px tile at low intensity, repeated. It is what stops the
          scrim's long gradient from banding on a wide screen, and it is the
          reason the scrim can be this light without the footage looking
          digital. Generated by scripts/make-grain.mjs — not extractable from
          the reference. */}
      <div
        aria-hidden
        className="absolute inset-0 z-[2]"
        style={{
          backgroundImage: "url(/grain.png)",
          backgroundSize: "256px auto",
          backgroundRepeat: "repeat",
        }}
      />

      {/* Content container. `calc(100% - 100px)` reserves the logo band, and
          `justify-between` against the spacer below drives the content row to
          the bottom of the remaining space. */}
      <div className="relative z-10 shell flex h-[calc(100%-100px)] w-full flex-col items-center justify-between pt-9 pb-11">
        <div aria-hidden className="h-[71px] w-[110px] shrink-0" />

        {/* Two equal columns, BOTTOM-aligned. `items-end` is the defining
            detail of this composition: it puts the bottom edge of the CTA
            button and the bottom edge of the stat label on one baseline. Swap
            it for `items-center` or `items-start` and the whole hero stops
            matching the reference. */}
        <div className="flex w-full flex-col items-start justify-center gap-8 md:flex-row md:items-end md:gap-11">
          <div className="flex w-full flex-col items-start justify-center gap-8 md:flex-1 md:gap-9">
            <div className="flex flex-col items-start gap-4">
              <span className="eyebrow-pill rise">{hero.eyebrow}</span>

              {/* Two AUTHORED lines, not organic wrapping, with the first
                  word of each set in italic. The break is content, not
                  layout — see hero.titleLines in content/copy.ts. `max-w`
                  only guards against a wider viewport re-wrapping it. */}
              <h1 className="display hero-h1 rise max-w-[600px] text-[80px] text-white [animation-delay:80ms]">
                {hero.titleLines.map((line, i) => (
                  <span key={line.lead} className="block">
                    <em className="italic">{line.lead}</em>
                    {line.rest}
                    {i < hero.titleLines.length - 1 ? <br /> : null}
                  </span>
                ))}
              </h1>

              {/* Full column width — no narrower measure. The reference lets
                  this run the whole 678px column. */}
              <p className="rise w-full text-[18px] leading-[27px] text-white [animation-delay:160ms]">
                {hero.lede}
              </p>
            </div>

            {/* No caption beside the hero CTA. `hero.ctaNote` still exists and
                is rendered by the mid-page CTA blocks, which is where the
                reference puts that line. */}
            <CtaButton href="#get-in-touch" className="rise [animation-delay:240ms]">
              {hero.cta}
            </CtaButton>
          </div>

          <div className="rise hidden flex-col items-end gap-1.5 md:flex md:flex-1 [animation-delay:320ms]">
            <p className="numeral text-[40px] text-white">{hero.stat.value}</p>
            <p className="text-right text-[14px] leading-[21px] text-white">
              {hero.stat.label}
            </p>
          </div>
        </div>
      </div>

      {/* Logo band — full-bleed and OUTSIDE the shell, unlike the text above
          it. 100px tall, its own translucent blurred ground rather than a
          hairline rule. The label column is a fixed 231px so the marquee
          starts at the same x whatever the label says. */}
      <div
        className="relative z-10 flex h-[100px] w-full shrink-0 items-center justify-center gap-2.5 overflow-clip p-5"
        style={{
          background: "rgba(21,21,21,0.24)",
          backdropFilter: "blur(4px)",
        }}
      >
        <div className="flex h-[60px] w-full max-w-[1400px] items-center gap-4">
          <p className="strip-label hidden sm:block">{hero.stripLabel}</p>
          <LogoMarquee itemClassName="h-7 w-24" />
        </div>
      </div>
    </section>
  );
}
