import { CtaButton } from "@/components/ui/button";
import { hero } from "@/content/copy";
import { LogoMarquee } from "@/components/ui/logo-marquee";

/**
 * Full-bleed background video behind the headline.
 *
 * Server component — no JS. The poster sits on the wrapper as a background
 * image and the video paints over it, so hiding the video under
 * `prefers-reduced-motion` (see globals.css) leaves the still frame in place
 * with no script and no flash.
 *
 * `muted` and `playsInline` are both load-bearing: iOS Safari refuses to
 * autoplay without them. `poster` also covers the gap before first frame.
 *
 * Height is an exact `h-dvh`, not a `min-h`. The composition depends on it:
 * the content container is `calc(100% - 100px)`, reserving the logo band, and
 * a min-height would let a long line push the band off the fold. `dvh` rather
 * than `vh` because on mobile the collapsing URL bar changes `vh` mid-scroll
 * and the hero would visibly resize under the reader.
 *
 * The negative margin cancels the padding `main` reserves for the chrome, so
 * the hero starts at y:0 with the bar and nav floating over it.
 */
export function Hero() {
  return (
    <section className="relative isolate -mt-[var(--header-h)] flex h-dvh flex-col items-center overflow-clip bg-ground">
      {/* Background stack: video (0), scrim (1), grain (2), content (10).
          POSITIVE z-indexes on purpose. These were -30/-20/-10 with the
          content at auto, which renders identically but buries the video
          three layers deep behind the section's own background — and Chrome
          then treats it as occluded and stops decoding, so the hero silently
          freezes on its poster while `currentTime` keeps advancing. Keep the
          video in normal stacking order. */}
      <div
        aria-hidden
        className="absolute inset-0 z-0 bg-ground bg-cover bg-center"
        style={{ backgroundImage: "url(/video/hero-poster.webp)" }}
      >
        <video
          className="hero-video h-full w-full object-cover"
          autoPlay
          muted
          loop
          playsInline
          preload="auto"
          poster="/video/hero-poster.webp"
          tabIndex={-1}
        >
          {/* `media` filters the source list before selection, so under
              reduced motion nothing is fetched at all — not fetched and then
              hidden. The poster behind is already doing the work. */}
          <source
            src="/video/hero.webm"
            type="video/webm"
            media="(prefers-reduced-motion: no-preference)"
          />
          <source
            src="/video/hero.mp4"
            type="video/mp4"
            media="(prefers-reduced-motion: no-preference)"
          />
        </video>
      </div>

      {/* Scrim — TWO stops, 0.44 to 0.60, in the ground colour rather than in
          black. This replaced a five-stop gradient that opened at 0.93 and was
          derived per-clip from measured band luma; it crushed the footage and
          the sky went with it.

          What makes two stops safe here is that nothing in the text block
          relies on the scrim any more: every run in the hero is pure white,
          the type is much larger than it was, and the reference sets it the
          same way. If a future clip has a blown highlight drifting under the
          text, re-derive rather than deepening this uniformly. */}
      <div
        aria-hidden
        className="absolute inset-0 z-[1]"
        style={{
          backgroundImage:
            "linear-gradient(rgba(21,21,21,0.44) 0%, rgba(21,21,21,0.60) 105%)",
        }}
      />

      {/* Grain. A 256px tile at low intensity, repeated. It is what stops the
          scrim's long gradient from banding on a wide screen, and it is the
          reason the scrim can be this light without the footage looking
          digital. Generated by scripts/make-grain.mjs — not extractable from
          the reference. */}
      <div
        aria-hidden
        className="absolute inset-0 z-[2]"
        style={{
          backgroundImage: "url(/grain.png)",
          backgroundSize: "256px auto",
          backgroundRepeat: "repeat",
        }}
      />

      {/* Content container. `calc(100% - 100px)` reserves the logo band, and
          `justify-between` against the spacer below drives the content row to
          the bottom of the remaining space. */}
      <div className="relative z-10 shell flex h-[calc(100%-100px)] w-full flex-col items-center justify-between pt-9 pb-11">
        <div aria-hidden className="h-[71px] w-[110px] shrink-0" />

        {/* Two equal columns, BOTTOM-aligned. `items-end` is the defining
            detail of this composition: it puts the bottom edge of the CTA
            button and the bottom edge of the stat label on one baseline. Swap
            it for `items-center` or `items-start` and the whole hero stops
            matching the reference. */}
        <div className="flex w-full flex-col items-start justify-center gap-8 md:flex-row md:items-end md:gap-11">
          {/* `@container` makes this column the reference for the H1's `cqw`
              size — see the note on the h1. It is inline-size containment
              only, so it constrains nothing this column was relying on. */}
          <div className="@container flex w-full flex-col items-start justify-center gap-8 md:flex-1 md:gap-9">
            <div className="flex flex-col items-start gap-4">
              <span className="eyebrow-pill rise">{hero.eyebrow}</span>

              {/* Two AUTHORED lines, not organic wrapping. The break is
                  content, not layout — see hero.titleLines in
                  content/copy.ts.

                  THE SIZE IS DERIVED FROM THE LINE, NOT CHOSEN.
                  "advisory with an edge" is the longer authored line and it
                  must never wrap — a third line is the bug this whole
                  expression exists to prevent. Measured in the browser at the
                  real weight and tracking:

                    Cormorant 80px / -0.04em  ->  607px   (old face)
                    Satoshi   72px / -0.025em ->  674px   wraps
                    Satoshi   64px / -0.025em ->  599px   fits

                  Satoshi is ~12% wider than Cormorant at the SAME nominal
                  size, so holding the break costs more size than the optical
                  match alone suggests: the rest of the display scale moved
                  80->72, this one had to go to 64. Hence its own `hero-h1`
                  class rather than `display-72`.

                  WHY cqw AND NOT A FIXED 64px. This column is `flex-1` of a
                  two-column row from 768px up, so it is only 342px wide at
                  768 and 598px at 1280 — a fixed 64px line (599px) wraps
                  everywhere below ~1282px. `cqw` is 1% of THIS COLUMN, so the
                  headline is sized by the space it actually has instead of by
                  the viewport. The ratio is the measurement: the line is
                  599/64 = 9.36x the font size, so it fits while
                  size <= colW/9.36, i.e. 10.68cqw. 10.4 is that with margin.

                  This is the clamp the note in globals.css warns against — an
                  arbitrary one reflows the authored break. This one is
                  derived FROM the break and is the thing keeping it. The
                  809px step-down was removed with it; it is no longer needed
                  and would fight this.

                  `max-w-[660px]` caps the measure once the column is wider
                  than the line needs. It was 600px, and Cormorant's 607px
                  line had been overflowing it by 7px — the break was
                  surviving on the browser's willingness to overflow rather
                  than by fitting. If the headline copy changes, re-measure
                  the longest line and re-derive; do not nudge the numbers.

                  THE LEAD WORDS ARE NO LONGER ITALIC. They were, under
                  Cormorant, which carried a real drawn italic. Satoshi is
                  roman-only here — no `ital` or `slnt` axis — so an <em> would
                  render as a browser-synthesised slant on the largest type on
                  the site. The site's earlier Satoshi build set nothing in
                  italic for exactly this reason. `lead` and `rest` are kept
                  apart because they are still the authored line break; they
                  simply no longer differ in style. Do not put the <em> back
                  without shipping Satoshi-VariableItalic.woff2. */}
              <h1 className="display hero-h1 rise max-w-[660px] text-[clamp(1.75rem,10.4cqw,64px)] text-white [animation-delay:80ms]">
                {hero.titleLines.map((line, i) => (
                  <span key={line.lead} className="block">
                    {line.lead}
                    {line.rest}
                    {i < hero.titleLines.length - 1 ? <br /> : null}
                  </span>
                ))}
              </h1>

              {/* Full column width — no narrower measure. The reference lets
                  this run the whole 678px column. */}
              <p className="rise w-full text-[18px] leading-[27px] text-white [animation-delay:160ms]">
                {hero.lede}
              </p>
            </div>

            {/* No caption beside the hero CTA. `hero.ctaNote` still exists and
                is rendered by the mid-page CTA blocks, which is where the
                reference puts that line. */}
            <CtaButton href="/get-in-touch" className="rise [animation-delay:240ms]">
              {hero.cta}
            </CtaButton>
          </div>

          <div className="rise hidden flex-col items-end gap-1.5 md:flex md:flex-1 [animation-delay:320ms]">
            <p className="numeral text-[36px] text-white">{hero.stat.value}</p>
            <p className="text-right text-[14px] leading-[21px] text-white">
              {hero.stat.label}
            </p>
          </div>
        </div>
      </div>

      {/* Logo band — full-bleed and OUTSIDE the shell, unlike the text above
          it. 100px tall, its own translucent blurred ground rather than a
          hairline rule. The label column is a fixed 231px so the marquee
          starts at the same x whatever the label says. */}
      <div
        className="relative z-10 flex h-[100px] w-full shrink-0 items-center justify-center gap-2.5 overflow-clip p-5"
        style={{
          background: "rgba(21,21,21,0.24)",
          backdropFilter: "blur(4px)",
        }}
      >
        <div className="flex h-[60px] w-full max-w-[1400px] items-center gap-4">
          <p className="strip-label hidden sm:block">{hero.stripLabel}</p>
          <LogoMarquee itemClassName="h-7 w-24" />
        </div>
      </div>
    </section>
  );
}
