/**
 * Venture-firm marks for the strip at the foot of the /customers hero,
 * mirroring the one fundraisr.ai runs there. Generated by
 * scripts/fetch-ecosystem-logos.mjs — regenerate rather than hand-edit.
 *
 * These are NOT the client logos in content/client-logos.ts, and the two must
 * not be mixed:
 *
 *  - These are full-colour marks meant for a light ground. They are NOT
 *    processed by scripts/logos-to-alpha.mjs and must never carry the
 *    `logo-mark` class, which would invert them to white on a white band.
 *  - They make no claim of a client relationship. The strip's caption says so
 *    (`customers.ecosystemNote`); the client disclaimer (`customers.logoNote`)
 *    belongs to the roster grid further down the page.
 *
 * Nine, not ten: the tenth source file 404s on fundraisr.ai and does not
 * render on their own page either.
 */

export const ecosystemLogos: string[] = [
  "/logos/ecosystem/tiger-global.webp",
  "/logos/ecosystem/sequoia.webp",
  "/logos/ecosystem/legend-capital.webp",
  "/logos/ecosystem/top5.webp",
  "/logos/ecosystem/lightspeed.webp",
  "/logos/ecosystem/top7.webp",
  "/logos/ecosystem/top8.webp",
  "/logos/ecosystem/top9.webp",
  "/logos/ecosystem/dragoneer.webp",
];
