/**
 * GENERATED by scripts/secondary-logos.mjs — do not edit by hand.
 *
 * The marks in the "Direct access" band at the foot of
 * /solutions/secondaries. White-on-transparent, so they carry `logo-mark`
 * at the call site and survive a light band the way the client roster does.
 *
 * **THREE OF THESE ARE NAMED FOR THE FILE THEY ARRIVED AS, not for a
 * company.** `4un8cuhsizzbjhizk1guxg`, `6x5fvvef17kxyxztakoerz` and
 * `gtck8vd6paoisp1w85sma` were supplied with hash filenames and no
 * captions, and a mark is a claim about who we have access to — so they are
 * NOT guessed at. Rename the master in docs/assets/secondary-logos/ and
 * re-run the script once the companies are confirmed. Nothing renders a
 * name: the grid sets `alt=""`, so an unnamed file states nothing it
 * cannot support.
 */

export const secondaryLogos: readonly string[] = [
  "/logos/secondaries/4un8cuhsizzbjhizk1guxg.webp",
  "/logos/secondaries/6x5fvvef17kxyxztakoerz.webp",
  "/logos/secondaries/crusoe.webp",
  "/logos/secondaries/elevenlabs.webp",
  "/logos/secondaries/gtck8vd6paoisp1w85sma.webp",
  "/logos/secondaries/kalshi.webp",
  "/logos/secondaries/lovable.webp",
  "/logos/secondaries/polymarket.webp",
  "/logos/secondaries/revolut.webp"
];
