/**
 * GENERATED by scripts/optimize-team-photos.mjs — do not edit by hand.
 *
 * One 12x15 WebP per portrait, inlined as a data URI and handed to
 * next/image as `blurDataURL`. Without it the portraits are lazy with no
 * placeholder, so scrolling the team section before they decode shows five
 * empty bordered frames on the dark band — which reads as a broken slab
 * rather than as loading, because the frame's own `bg-ground-alt` is the
 * same #151515 as the band behind it.
 *
 * Keyed on the PUBLIC PATH rather than a slug, because that is what
 * content/team.ts stores and it is the thing that has to match.
 */

export const teamBlur: Record<string, string> = {
  "/team/bernardo-almeida.webp":
    "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoMAA8AA4BaJaQAD4kNKwYKcAAA/uIZhJ5b24/gNxZh9b+8nhdlcMOjI+os+XlbgfUwOe2SC3QwS8PxNxHfY6EBY8/fP60MwAA=",
  "/team/lev-valestkiy.webp":
    "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoMAA8AA4BaJaQAAlxjch20PAAA/ut1fEeRjc/5hWb9F2yzkNzkPToMPPfIPf7KgG3sZMpX8GLOrzlZ1NDJO9lm+FgTf/jTJ4fR4AAA",
  "/team/bruno-erckmam.webp":
    "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoMAA8AA4BaJaQAD4hKR0B2ZQGAAP7uGc5T+OuwYnh5Dfk8NcR1/Mwk5aoJSAITbMrh1P5GtSaIpe2+I5x3228fs9is64yWIfIoqIJSld3IEFKhkbcPgAAA",
  "/team/tatjana-sotirovik.webp":
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoMAA8AA4BaJaQAAq8t0ji8HAAA/sPuMCwA2IS66svGfOZT/O7DYFTcdRGyPcyu+f9rmutKQMxQmNxzMoGn76Rwx0gCXFES54TovD/wzAAAAA==",
  "/team/lucas-barrozo.webp":
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoMAA8AA4BaJaQAAi/hlrL/CAD+7ibr6ceVmZe+pewJVrVAoZ+WIOhqnZW6gyWRzNiWrm/83w8VsVHr77/0OKYcYf7OhkPYzibPyQvsbkfwAA==",
};
