/**
 * GENERATED by scripts/optimize-team-photos.mjs - do not edit by hand.
 *
 * One 12x15 WebP per portrait, inlined as a data URI and handed to
 * next/image as `blurDataURL`. Without it the portraits are lazy with no
 * placeholder, so scrolling the team section before they decode shows five
 * empty bordered frames on the dark band - which reads as a broken slab
 * rather than as loading, because the frame's own `bg-ground-alt` is the
 * same #151515 as the band behind it.
 *
 * Keyed on the PUBLIC PATH rather than a slug, because that is what
 * content/team.ts stores and it is the thing that has to match.
 */

export const teamBlur: Record<string, string> = {
  "/team/bernardo-almeida.webp": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAQCdASoMAA8AA4BaJaQAAY9KaKAA/snJQVfvEJkCHc48e9D5X+sqBDoY12xnnDiHoWQ5wvlmbnn9EiIkrsZmo68wAV4mhxAOQ6QAAAA=",
  "/team/lev-valestkiy.webp": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoMAA8AA4BaJaQAAxYSCV6SRJgAAP7XLUAFviOCEZfBlc9ETCIarnbGWgmHv9UIuskzGznB6vOVnU0op3TX0FlvBP6nVjE0AAA=",
  "/team/bruno-erckmam.webp": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoMAA8AA4BaJaQAD4/Q++Lk3um8sAD+4Wks/jtK2tzUjzmO4/QFzIynVkkl9jUmoz0J2R4nfqVr5T7XqE0nkO2ZRGpQ2c8MDggMVrFtkvWDAAAA",
  "/team/tatjana-sotirovik.webp": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoMAA8AA4BaJaQAAq58KMV+AAD+yDmY2DwVFMNFqxl0kBtucRMZIqbjqI2RG/yKuhYS9LqnK+uCaFrruUfRVh50awtVTrYmNLiTlGxqZExgAA==",
  "/team/lucas-barrozo.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoMAA8AA4BaJaQAAi6YMRHSAAD+1v+LjCH6pXTynx06HG1FY+KaLFh2BblR9gtZS8S/Ba+WAsxTLsI/Z8bcmbaokvq9QHuicBnaMrvVgAA=",
  "/team/arsenio-renato.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoMAA8AA4BaJaQAAl0jmX8QYAAA/sX7I3aTOk5TF3d8/v7YuEEAF4mL1ClmhB4TpkfwmxDBWSd/IYgB5/R547k3k9exhrxWUabyf6oAAAA=",
  "/team/account-executive-01.webp": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoMAA8AA4BaJaQAAv93/flLrWAAAP7roshGEOjnuyeC3TfwtA6JUAOVoW9KRaAcPsl7o+6hpXxJRq3/IGbnHg1laofaw7Uf9qZvfA3nwe2Pz1AA",
  "/team/account-executive-02.webp": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoMAA8AA4BaJaQAAlrvIxNkAAD+66LGMX83cO6TgiYs6GcqgBJl4rXwn+XrMK9gTvqVTRXn44lzYSlqnR/wPtTqr/AAAA=="
};
